config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    # resources :social_sharing isn't playing nicely in our extension
    match "social-sharing" => "social_sharing#index", :as => :social_sharing
    match "social-sharing/edit" => "social_sharing#edit", :as => :edit_social_sharing
    match "social-sharing/update" => "social_sharing#update", :as => :update_social_sharing
  end
end

app/models/social_sharing.rb
class SocialSharing
  FACEBOOK_PREFS = ['use_facebook_on_site_footer', 'use_facebook_on_products','facebook_page_or_other_url','facebook_style', 'facebook_width','facebook_font', 'facebook_color_scheme', 'facebook_verb_to_display']
  GOOGLE_PREFS = ['use_google_on_products', 'use_google_on_site_footer', 'google_style', 'google_annotation']
  TWITTER_PREFS = ['use_twitter_tweets_on_products', 'use_twitter_tweets_on_site_footer', 'use_twitter_name','twitter_tweets_show_count', 'twitter_tweets_size_is_large', 'twitter_tweets_hash_tag']
  FACEBOOK_FONTS = ["arial", "tahoma", "verdana", "lucida grande", "segoe ui", "trebuchet ms"]
  FACEBOOK_STYLES = ["standard", "button_count", "box_count"]
  FACEBOOK_COLOR_SCHEMES = ["light", "dark"]
  FACEBOOK_VERBS = ["like", "recommend"]
  GOOGLE_STYLES = ["inline", "bubble", "none"]
  GOOGLE_ANNOTATIONS = ["small", "standard", "medium", "tall"]
  
  def self.facebook_attributes(parent, url, attribs='')
    attribs << "data-href='#{share_url("facebook", parent, url)} '" 
    attribs << "data-send='false'"
    attribs << "data-layout='#{Spree::Config[:facebook_style]}' "
    attribs << "data-width='#{Spree::Config[:facebook_width]}' "
    attribs << "data-show-faces='false' "
    attribs << "data-action='recommend' " if Spree::Config["facebook_verb_to_display"] != "like"
    attribs << "data-colorscheme='#{Spree::Config[:facebook_color_scheme]}' "
    attribs << "data-font='#{Spree::Config[:facebook_font]}'"
  end
  
  def self.share_url(provider, parent, url)
    # different URLs to share for different buttons. 
    # I.e., The footer's like button should "Like" the homepage, unlike the product's
    provider == "facebook" ?
    parent == 'product' ? url : Spree::Config['facebook_page_or_other_url']
    : parent == "product" ? url :  Spree::Config[:site_url]
  end
  
  def self.twitter_attributes(parent, url, attribs='')
    attribs << ("data-hash_tags='#{Spree::Config[:twitter_tweets_hash_tag]}' " if Spree::Config[:twitter_tweets_hash_tag].present?)
    attribs << ("data-via='#{Spree::Config[:use_twitter_name]}' " if Spree::Config[:use_twitter_name].present?)
    attribs << ("data-count='none' " if Spree::Config[:twitter_tweets_show_count] == true)
    attribs << ("data-size='large'" if Spree::Config[:twitter_tweets_size_is_large] == true)
    attribs << share_url("twitter", parent, url)
  end
  
  def self.google_attributes(parent, url, attribs = '')
    attribs << "ansize='#{Spree::Config[:google_style]}' "
    attribs <<  "href='#{share_url("google", parent, url)}' "
    attribs <<  "annotation='#{Spree::Config[:google_annotation]}'"
  end

  # Returns all preferences for a given provider
  def self.preferences_for(provider)
    case provider
    when "facebook" then FACEBOOK_PREFS
    when "twitter" then TWITTER_PREFS
    when "google" then GOOGLE_PREFS
    end
  end
  
  def self.all_prefs
    preferences_for("facebook") + preferences_for("google") + preferences_for("twitter")
  end

  # Manage our attributes from different providers
  def self.style_options_for(provider, attribute)
    if provider == "facebook"
      case attribute
        when "fonts" then FACEBOOK_FONTS
        when "styles" then FACEBOOK_STYLES
        when "color_schemes" then FACEBOOK_COLOR_SCHEMES
        when "verbs" then FACEBOOK_VERBS
      end
    elsif provider == "google"
      case attribute
        when "styles" then GOOGLE_STYLES
        when "annotations" then GOOGLE_ANNOTATIONS
      end
    end
  end
end

app/models/spree/app_configuration_decorators.rb
Spree::AppConfiguration.class_eval do
  # Share button previews for Facebook, Twitter, Google+ (in Admin)
  preference :preview_enabled, :boolean, :default => true
  
  # Facebook Like options
  preference :use_facebook_on_site_footer, :boolean, :default => true
  preference :facebook_page_or_other_url, :string
  preference :use_facebook_on_products, :boolean, :default => true
  preference :facebook_style , :string, :default => "standard"
  preference :facebook_width, :integer, :default => 200
  preference :facebook_verb_to_display, :string, :default => "like"
  preference :facebook_color_scheme, :string, :default => "light"
  preference :facebook_font, :string, :default => "arial"
  
  # Google +1 options
  preference :use_google_on_site_footer, :boolean, :default => true
  preference :use_google_on_products, :boolean, :default => true
  preference :google_style, :string, :default => "medium"
  preference :google_annotation, :string, :default => "bubble"
  
  # Twitter tweeting options
  preference :use_twitter_tweets_on_products, :boolean, :default => true
  preference :use_twitter_tweets_on_site_footer, :boolean, :default => true
  preference :use_twitter_name, :string
  preference :twitter_tweets_show_count, :boolean, :default => true
  preference :twitter_tweets_size_is_large, :boolean, :default => true
  preference :twitter_tweets_hash_tag, :string
end

app/controllers/admin/social_sharing_controller.rb
class Admin::SocialSharingController < Spree::Admin::BaseController
  
  def index
    @preferences_fb = SocialSharing.preferences_for("facebook")
    @preferences_google = SocialSharing.preferences_for("google")
    @preferences_twitter = SocialSharing.preferences_for("twitter")
  end
  
  def edit
    @preferences = SocialSharing.all_prefs
  end
  
  def update
    params.each do |name, value|
      next unless Spree::Config.has_preference? name
      Spree::Config[name] = value
    end

    respond_to do |format|
      format.html {
        flash[:notice] = t(:social_sharing_updated)
        redirect_to social_sharing_path
      }
    end
  end
end

app/helpers/social_sharing_helper.rb
module SocialSharingHelper
  # Key parameter represents a preference's name which is equivalent to a social share button option like color or size.
  # Type parameter is the data type of the preference i.e., :boolean
  def social_sharing_selects(key, type)
    case key
      # FIXME
      when "facebook_font" then select_tag(key, social_opts_for(key, SocialSharing.style_options_for("facebook", "fonts")))
      when "facebook_style" then select_tag(key, social_opts_for(key, SocialSharing.style_options_for("facebook", "styles")))
      when "facebook_color_scheme" then select_tag(key, social_opts_for(key, SocialSharing.style_options_for("facebook", "color_schemes")))
      when "facebook_verb_to_display" then select_tag(key, social_opts_for(key, SocialSharing.style_options_for("facebook", "verbs")))
      when "google_style" then select_tag(key, social_opts_for(key, SocialSharing.style_options_for("google", "styles")))
      when "google_annotation" then select_tag(key, social_opts_for(key, SocialSharing.style_options_for("google", "annotations")))
      else preference_field_tag(key, Spree::Config[key], :type => type)
    end
  end
  
  # Returns host & URI, good for sharing
  def url
    url_for(:only_path => false)
  end
  
  def render_sharing_for(target, provider)
    if target == "footer"
      # The "parent" parameter helps us know which URL we need to share for this rendition
      # I.e., the Facebook button on the footer should link to Company facebook, not the URL it's on
      case provider
        when "facebook" then render :partial => 'spree/shared/facebook_likes', :locals => { :sender => "footer" } if Spree::Config[:use_facebook_on_products]
        when "twitter" then render :partial => 'spree/shared/twitter_tweets', :locals => { :sender => "footer" } if Spree::Config[:use_twitter_tweets_on_products] 
        when "google" then render :partial => 'spree/shared/google_plusones', :locals => { :sender => "footer"} if Spree::Config[:use_google_on_site_footer]
      end
    elsif target == "product"
      case provider
        when "facebook" then render :partial => 'spree/shared/facebook_likes', :locals => { :sender => "product" } if Spree::Config[:use_facebook_on_products]
        when "twitter" then render :partial => 'spree/shared/twitter_tweets', :locals => { :sender => "product"} if Spree::Config[:use_twitter_tweets_on_site_footer]
        when "google" then render :partial => 'spree/shared/google_plusones', :locals => { :sender => "product" } if Spree::Config[:use_google_on_products]
      end
    end
  end
  
  def sent_from_product?(object)
    object == "product" ? true : false
  end
  
  def social_opts_for(key, select_list)
    options_for_select(select_list, :selected => Spree::Config[key])
  end
end

app/views/admin/social_sharing/_preview.html.erb
<% if Spree::Config['preview_enabled'] %>
<div style="padding: 30px; border: 1px dashed red; width: 775px;background-color:#FFFFCC; text-align: center">
    <%= render :partial => 'spree/shared/twitter_tweets', :locals => { :sender => "admin"} %>
    <%= render :partial => 'spree/shared/facebook_likes', :locals => { :sender => "admin" } %>
    <%= render :partial => 'spree/shared/google_plusones', :locals => { :sender => "admin"} %>
    <br /><br /><br />
    <p><%= t(:previews_can_be_disabled) %> <a href="/admin/social-sharing/edit"><%= t(:here)%></a></p>
</div>
<% else %>
<p><%= t(:previewing_has_been_disabled) %></p>
<% end %>

app/views/admin/social_sharing/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:edit_social_sharing_settings) %></h1>

<%= form_tag update_social_sharing, :method => :put  do |form| %>
  <%= label_tag( t('preview_enabled') )  %>
  <%= preference_field_tag('preview_enabled', Spree::Config['preview_enabled'], :type => :boolean) %>
  <br /><br />
  <fieldset id="preferences" data-hook>
  <% @preferences.each do |key|  %>
      <% type = Spree::Config.preference_type(key) %>
      <%= label_tag(key, t(key) + ': ') + tag(:br) if type != :boolean %>
      <%= social_sharing_selects(key, type) %>
      <%= label_tag(key, t(key)) + tag(:br) + tag(:br) if type == :boolean %>
      <%= tag(:br)  + tag(:br) if type != :boolean %>
  <% end %>
  </fieldset>
  <p class="form-buttons" data-hook="buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_general_settings_url %>
  </p>
<% end %>

app/views/admin/social_sharing/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:social_sharing_settings) %></h1>

<%= render :partial => "preview", :locals => { :from => "admin" } %>

<table data-hook="preferences">
  <tr>
    <th scope="row" style="font-size:22px"><%= t(:facebook) %></th>
    <td>&nbsp;</td>
  </tr>
  <% @preferences_fb.each do |key| %>
  <tr>
    <th scope="row"><%= t(key) %>:</th>
    <td><%= Spree::Config[key] %></td>
  </tr>
  <% end %>
  <tr>
    <th scope="row" style="font-size:22px;"><%= t(:google) %></th>
    <td>&nbsp;</td>
  </tr>
  <% @preferences_google.each do |key| %>
  <tr>
    <th scope="row"><%= t(key) %>:</th>
    <td><%= Spree::Config[key] %></td>
  </tr>
  <% end %>
  
  <tr>
    <th scope="row" style="font-size:22px"><%= t(:twitter) %></th>
    <td>&nbsp;</td>
  </tr>
  <% @preferences_twitter.each do |key| %>
  <tr>
    <th scope="row"><%= t(key) %>:</th>
    <td><%= Spree::Config[key] %></td>
  </tr>
  <% end %>

</table>

<p><%= link_to_with_icon 'edit', t(:edit), edit_social_sharing_path, :id => 'admin_general_settings_link' %></p>

app/views/spree/products/_social_sharing.html.erb
<%= render_sharing_for("product", "twitter") %>

<%= render_sharing_for("product", "facebook") %>

<%= render_sharing_for("product", "google") %>

app/views/spree/products/_social_sharing_js.html.erb
<!-- Facebook JS -->
<% if Spree::Config[:use_facebook_on_products] %>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<% end %>

<!-- Google JS -->
<% if Spree::Config[:use_google_on_products] %>
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
<% end %>

<!-- Tiwitter JS -->
<% if Spree::Config[:use_twitter_tweets_on_products] %>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<% end %>

app/views/spree/shared/_facebook_likes.html.erb
<div class="fb-like" <%= SocialSharing.facebook_attributes(sender, url) %>></div>

<% content_for :head do %>
  <% if @product %>
    <%= tag('meta', :property => 'title', :content => @product.name) %>
    <%= tag('meta', :property => 'description', :content => @product.meta_description) if @product.meta_description.present? %>
    <%= tag('meta', :property => 'img_src', :content => "http://#{Spree::Config[:site_url]}#{@product.images.first.attachment.url(:product)}") if @product.images.first %>
  <% end %>
<% end %>

app/views/spree/shared/_google_plusones.html.erb
<g:plusone <%= SocialSharing.google_attributes(sender, url) %>></g:plusone>

<% content_for :head do %>
  <% if @product %>
    <meta itemprop="name" content="<%= @product.name %>">
    <meta itemprop="description" content="<%= @product.meta_description if @product.meta_description.present? %>">
    <meta itemprop="image" content="<%= "http://#{Spree::Config[:site_url]}#{@product.images.first.attachment.url(:product)}" if @product && @product.images.first %>">
  <% end %>
<% end %>

app/views/spree/shared/_social_sharing_footer.html.erb
<%= render_sharing_for("footer", "twitter") %>

<%= render_sharing_for("footer", "facebook") %>

<%= render_sharing_for("footer", "google") %>

app/views/spree/shared/_twitter_tweets.html.erb
<a href="https://twitter.com/share" class='twitter-share-button' <%= SocialSharing.twitter_attributes(sender, url) %>>Tweet</a>